phishman3579/java-algorithms-implementation

src/com/jwetherell/algorithms/mathematics/Primes.java, src/com/jwetherell/algorithms/mathematics/test/Mathematics.java
Spot some mistakes on that, I just added some more test cases
=> corrected sieveOfEratosthenes, added test case

README.md, src/com/jwetherell/algorithms/graph/Kruskal.java, test/com/jwetherell/algorithms/graph/test/Graphs.java
I added Kurskal algorithm. It solves the same problem as Prim's so I reused your tests.
I'm not sure if condition at Prim's test (resultMST.equals(idealMST)) is correct. Nevermind, I compare only costs.
If you have any comments, feel free to tell it to me.
=> Added Kurskal's algorithm

README.md, src/com/jwetherell/algorithms/search/LowerBound.java, src/com/jwetherell/algorithms/search/UpperBound.java, src/com/jwetherell/algorithms/sequence/LongestIncreasingSubsequence.java, test/com/jwetherell/algorithms/search/test/Search.java, test/com/jwetherell/algorithms/sequence/test/Sequences.java
I wanted to add longest increasing subsequence but it needs lower bound algorithm. So I added lower bound and upper bound algorithms too.
=> Longest increasing subsequence

src/com/jwetherell/algorithms/mathematics/Coprimes.java, src/com/jwetherell/algorithms/mathematics/Utils.java, test/com/jwetherell/algorithms/mathematics/test/GCD.java, test/com/jwetherell/algorithms/mathematics/test/Totient.java
I've added some math stuff. I hope that today or tomorrow I will add some algorithms in modular arithmetic (division, power and maybe discrete logarithm).
=> Euler's totient function and greatest common divisor

README.md
Section "Path" had general graphs algorithms, hence the change
=> Changes section name to "Graphs", adds Push-relabel to readme

README.md, src/com/jwetherell/algorithms/mathematics/Modular.java, test/com/jwetherell/algorithms/mathematics/test/ModularArithmetic.java
New pull requests after @mciancia changes
=> Modular arithmetic

README.md, src/com/jwetherell/algorithms/strings/Rotation.java, test/com/jwetherell/algorithms/strings/test/StringRotation.java
Implementation of Duval's algorithm.
=> Lexicographically minimal/maximal string rotation

README.md, src/com/jwetherell/algorithms/sequence/LargestSumContiguousSubarray.java, src/com/jwetherell/algorithms/sequence/LongestPalindromicSubsequence.java, test/com/jwetherell/algorithms/sequence/test/Sequences.java
Hello, I have added the Largest sum of contiguous subarray using Kadane's algorithm and also the Longest palin­dromic sub­se­quence using the dynamic programming approach.
=> Largest sum of contiguous subarray and Longest palin­dromic sub­se­quence

src/com/jwetherell/algorithms/mathematics/Multiplication.java, test/com/jwetherell/algorithms/mathematics/test/Mathematics.java
I added a new method to multiply two numbers with String input to Multiplication class which uses loop to multiply . This method uses the **Chinese multiplication method** of multiplying each number and then adding diagonals. Please merge my changes . If any change is needed just message me.
=> Added multiply using loop with string input.

README.md, src/com/jwetherell/algorithms/graph/DepthFirstTraversal.java
Yes! Pease reviews it.
I'm looking forward to more contribution.
FIxed #39
=> Depth First Traversal

src/com/jwetherell/algorithms/data_structures/DisjointSet.java
Hello
This is the PR for the issue #43.
Thanks!
=> Fixed for a wrong object equals (#43)

README.md
=> URL changes

src/com/jwetherell/algorithms/strings/Manacher.java, test/com/jwetherell/algorithms/strings/test/ManacherTests.java
=> Added Manacher's algorithm

README.md, src/com/jwetherell/algorithms/mathematics/Exponentiation.java, test/com/jwetherell/algorithms/mathematics/test/ExponentiationTest.java, test/com/jwetherell/algorithms/mathematics/timing/ExponentiationTiming.java
Hello! I wanted to add some algorithms but I need these power algorithms first so I made this PR.
PS, sorry for previous broken PR, shame on me.
=> Added exponentiation algorithms.

README.md, src/com/jwetherell/algorithms/mathematics/Exponentiation.java, src/com/jwetherell/algorithms/mathematics/Primes.java, test/com/jwetherell/algorithms/mathematics/test/ExponentiationTest.java, test/com/jwetherell/algorithms/mathematics/test/Mathematics.java
Hello! I added Miller-Rabin primality test.
This PR also contains a fix for power modulo with better tests.
=> Miller-Rabin test

README.md, src/com/jwetherell/algorithms/graph/TurboMatching.java, test/com/jwetherell/algorithms/graph/test/TurboMatchingTest.java
=> Added Turbo Matching

README.md, src/com/jwetherell/algorithms/data_structures/SuffixArray.java, src/com/jwetherell/algorithms/graph/TurboMatching.java, test/com/jwetherell/algorithms/data_structures/test/SuffixArrayTest.java, test/com/jwetherell/algorithms/graph/test/TurboMatchingTest.java
=> Added Suffix Array

README.md, src/com/jwetherell/algorithms/data_structures/LCPArray.java, src/com/jwetherell/algorithms/data_structures/SuffixArray.java, src/com/jwetherell/algorithms/graph/TurboMatching.java, test/com/jwetherell/algorithms/data_structures/test/LCPArrayTest.java, test/com/jwetherell/algorithms/data_structures/test/SuffixArrayTest.java, test/com/jwetherell/algorithms/graph/test/TurboMatchingTest.java
=> Added LCP array

src/com/jwetherell/algorithms/mathematics/DiscreteLogarithm.java, test/com/jwetherell/algorithms/mathematics/DiscreteLogarithmTest.java
=> adding discrete logarithm

.travis.yml, src/com/jwetherell/algorithms/data_structures/IntervalSumArray.java, test/com/jwetherell/algorithms/data_structures/IntervalSumArrayTest.java
This data structure allows finding sum of values in interval with O(log n) complexity.
=> Added interval sum array

src/com/jwetherell/algorithms/numbers/Integers.java
fix typo in src/Numbers/Integers.java
=> Fixed typo in Integers.java

src/com/jwetherell/algorithms/data_structures/List.java
=> Remove obsolete code

src/com/jwetherell/algorithms/numbers/Integers.java, test/com/jwetherell/algorithms/graph/test/Graphs.java, test/com/jwetherell/algorithms/numbers/test/Numbers.java
=> Fix Dijkstra test typo

src/com/jwetherell/algorithms/mathematics/Knapsack.java
Changed OR condition to &&,  OR may possibly result in ArrayIndexOutOfBoundException , (as it does for following input capacity : 60, weights: [10, 20, 33], values: [10, 3, 30]) 
Expected output is [2, 0]
=> Fixed while condition check in {Algorithm/Knapsack} 

README.md
=> Removed hedging and improved grammar in README.md

src/com/jwetherell/algorithms/search/BinarySearch.java
=> Added Comment on Linear Search Logic
